#!/bin/bash
$
# Run container in named server mode. Use this whne developing
# in REACT
#
#   * the container is named
#   * the npm/web server is running in dev mode
#   * exposed ports are mapped
#   * the app folder is directly mounted
#
CONTAINER_NAME=tetjs
APP_ROOT=$PWD/app

echo
echo "starting $CONTAINER_NAME with APP_ROOT=\"$APP_ROOT\"..."
echo

docker run -it --rm \
  --name $CONTAINER_NAME \
  -v $APP_ROOT:/root/app \
  -p 3000:3000 \
  tetjs-rapidant server
